[build-system]
requires = ["setuptools>=62.6"]
build-backend = "setuptools.build_meta"

[project]
name = "jumanji"
authors = [{ name = "InstaDeep Ltd", email = "clement.bonnet16@gmail.com" }]
dynamic = ["version"]
license = { file = "LICENSE" }
description = "A diverse suite of scalable reinforcement learning environments in JAX"
readme = "README.md"
requires-python = ">=3.10, <3.13"
keywords = ["reinforcement-learning", "python", "jax"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "License :: OSI Approved :: Apache Software License",
]
dependencies = [
    "chex>=0.1.3",
    "dill>=0.3.9",
    "dm-env>=1.5",
    "gymnasium>=1.0",
    "huggingface-hub",
    "jax>=0.5.2",
    "marimo>=0.12.4",
    "matplotlib==3.7.4",
    "multiprocess>=0.70.17",
    "mypy>=1.15.0",
    "pandas-stubs>=2.2.3.250308",
    "pillow>=9.0.0",
    "pre-commit>=4.2.0",
    "rl-zoo3>=2.5.0",
    "typing-extensions>=4.0.0",
    "vegafusion>=2.0.2",
    "vl-convert-python>=1.6.0",
    "wandb>=0.19.8",
]

[tool.setuptools.packages.find]
include = ["jumanji*"]

[tool.setuptools.package-data]
"jumanji" = [
    "py.typed",
    "environments/routing/mandl/assets/**/*.txt", # Include all .txt files in assets and subdirectories
    "environments/routing/mandl/assets/**/*.svg", # Include SVG files
    "environments/routing/mandl/assets/**/*.png", # Include PNG files
]

[tool.setuptools.dynamic]
version = { attr = "jumanji.version.__version__" }


[project.urls]
"Homepage" = "https://github.com/instadeep/jumanji"
"Bug Tracker" = "https://github.com/instadeep/jumanji/issues"
"Documentation" = "https://instadeepai.github.io/jumanji"

[tool.mypy]
python_version = "3.10"
namespace_packages = true
incremental = false
cache_dir = ""
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = false
allow_redefinition = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = false
strict_optional = true
strict_equality = true
explicit_package_bases = true
follow_imports = "skip"
exclude = ["jumanji/environments/routing/mandl/demo_notebook.py"]

[[tool.mypy.overrides]]
module = [
    "matplotlib.*",
    "mpl_toolkits.*",
    "gym.*",
    "pytest_mock.*",
    "numpy.*",
    "dm_env.*",
    "tree.*",
    "pytest.*",
    "IPython.*",
    "optax.*",
    "tqdm.*",
    "rlax.*",
    "neptune.*",
    "tensorboardX.*",
    "scipy.*",
    "haiku.*",
    "hydra.*",
    "omegaconf.*",
    "huggingface_hub.*",
    "requests.*",
    "pkg_resources.*",
    "PIL.*",
]
ignore_missing_imports = true

[tool.ruff]
line-length = 100
exclude = ["jumanji/environments/routing/mandl/demo_notebook.py"]

[tool.ruff.lint]
select = ["A", "B", "E", "F", "I", "N", "W", "RUF", "ANN"]
ignore = [
    "E731",   # Allow lambdas to be assigned to variables.
    "ANN101", # no need to type self
    "ANN102", # no need to type cls
    "ANN204", # no need for return type for special methods
    "ANN401", # can use Any type
    "A002",   # Argument shadowing a Python builtin.
    "A003",   # Class attribute shadowing a Python builtin.
    "A005",   # Module shadowing a Python builtin.
    "B017",   # assertRaises(Exception): or pytest.raises(Exception) should be considered evil.
    "F722",   # wrong error with forward annotation when using jaxtyping
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
    "F401",
] # Ignore `F401` (import violations) in all `__init__.py` files.

[project.optional-dependencies]
train = [
    "dm-haiku>=0.0.13",
    "hydra-core==1.3",
    "neptune-client==0.16.15",
    "optax>=0.1.4",
    "rlax>=0.1.4",
    "tensorboardX",
    "tqdm>=4.64.1",
]
dev = [
    "coverage>=7.6.12",
    "livereload>=2.7.1",
    "mkdocs==1.6.1",
    "mkdocs-autorefs==1.2.0",
    "mkdocs-git-revision-date-plugin==0.3.2",
    "mkdocs-include-markdown-plugin==7.1.1",
    "mkdocs-material==9.5.45",
    "mkdocs-mermaid2-plugin==1.1.0",
    "mkdocstrings[python]==0.27.0",
    "mknotebooks==0.8.0",
    "mypy>=1.15.0",
    "pandas-stubs>=2.2.3.250308",
    "pre-commit>=4.1.0",
    "promise>=2.3",
    "pymdown-extensions>=10.14.3",
    "pytest==7.0.1",
    "pytest-cov>=6.0.0",
    "pytest-mock>=3.14.0",
    "pytest-parallel>=0.1.1",
    "pytest-xdist>=3.6.1",
    "scipy>=1.7.3",
    "testfixtures>=8.3.0",
]
mandl = [
    "beartype>=0.20.0",
    "jaxtyping>=0.2.38",
    "sb3-contrib>=2.5.0",
    "sbx-rl>=0.20.0",
    "stable-baselines3>=2.4.0",
    "submitit>=1.5.2",
    "tensorboard>=2.0.0",
    "tyro>=0.9.17",
]
